# CodeClimate configuration for Go code quality analysis
# Documentation: https://docs.codeclimate.com/docs/advanced-configuration

version: "2"

# Configure which files and directories to analyze
exclude_patterns:
  - "vendor/"
  - "**/*_test.go"
  - "**/testdata/"
  - "**/*.pb.go"
  - ".github/"
  - "docs/"
  - "*.md"

# Configure which engines to run
checks:
  # Cognitive complexity check
  method-complexity:
    config:
      threshold: 15
  # Function length check  
  method-lines:
    config:
      threshold: 50
  # File length check
  file-lines:
    config:
      threshold: 300
  # Similar code detection
  similar-code:
    config:
      threshold: 50
  # Argument count check
  argument-count:
    config:
      threshold: 6

# Configure plugins
plugins:
  # Go language plugin
  gofmt:
    enabled: true
  govet:
    enabled: true
  golint:
    enabled: true
  # Security analysis
  sonar-go:
    enabled: true
    config:
      minimum_severity: minor

# Prepare commands to run before analysis
prepare:
  fetch:
    - url: "https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh"
      path: ".golangci-install.sh"
  - chmod +x .golangci-install.sh && ./.golangci-install.sh -b $(go env GOPATH)/bin latest
