# Docker Compose for local development
version: '3.8'

services:
  # Slack AI Bot
  slack-ai-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: slack-ai-bot
    restart: unless-stopped
    environment:
      # Slack Configuration
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      
      # AI Service Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      
      # Bot Configuration
      - BOT_NAME=${BOT_NAME:-AI Assistant}
      - DEBUG_MODE=${DEBUG_MODE:-false}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - MAX_CONVERSATION_HISTORY=${MAX_CONVERSATION_HISTORY:-10}
      
      # Redis connection (for conversation memory)
      - REDIS_URL=redis://redis:6379
      
      # Optional settings
      - RATE_LIMIT_PER_USER=${RATE_LIMIT_PER_USER:-30}
      - AI_REQUEST_TIMEOUT=${AI_REQUEST_TIMEOUT:-30}
      - ENABLE_CONVERSATION_MEMORY=${ENABLE_CONVERSATION_MEMORY:-true}
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - redis
    volumes:
      # Mount .env file for local development
      - ./.env:/app/.env:ro
    networks:
      - slack-bot-network
    healthcheck:
      test: ["CMD", "/slack-ai-bot", "--health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for conversation memory and caching
  redis:
    image: redis:7-alpine
    container_name: slack-ai-bot-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/etc/redis/redis.conf:ro
    command: redis-server /etc/redis/redis.conf
    networks:
      - slack-bot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Optional: Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: slack-ai-bot-redis-ui
    restart: unless-stopped
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - slack-bot-network
    profiles:
      - debug

volumes:
  redis_data:
    driver: local

networks:
  slack-bot-network:
    driver: bridge
